Repository maplibre/maplibre-gl-js, pull requests merged in 2022-09, with the labels that each got.

#1514 add freezeElevation logic to AnimationOptions
  src/render/draw_background.ts
  src/render/draw_circle.ts
  src/render/draw_collision_debug.ts
  src/render/draw_debug.ts
  src/render/draw_fill.ts
  src/render/draw_fill_extrusion.ts
  src/render/draw_hillshade.ts
  src/render/draw_line.ts
  src/render/draw_raster.ts
  src/render/draw_symbol.test.ts
  src/render/draw_symbol.ts
  src/render/painter.ts
  src/render/render_to_texture.test.ts
  src/render/render_to_texture.ts
  src/style/style.test.ts
  src/style/style.ts
  src/ui/camera.test.ts
  src/ui/camera.ts
  src/ui/control/terrain_control.ts
  src/ui/handler_manager.ts
  src/ui/map.test.ts
  src/ui/map.ts
  src/ui/marker.test.ts
  src/ui/marker.ts
  test/debug-pages/route.html
Labels: Terrain 3D

#1620 fix link in COMMUNITY.md
  COMMUNITY.md
Labels: waiting for code review fixes

#1629 Fix gl-stats
  test/bench/gl-stats.html
  test/bench/gl-stats.ts
Labels: waiting for code review fixes

#1622 More tests for sparse tilesets
  test/integration/assets/tiles/sparse/0-0-0.png
  test/integration/assets/tiles/sparse204/0-0-0.mvt
  test/integration/assets/tiles/sparse204/0-0-0.png
  test/integration/assets/tiles/sparse204/1-0-0.mvt
  test/integration/assets/tiles/sparse204/1-0-0.png
  test/integration/assets/tiles/sparse204/1-0-1.mvt
  test/integration/assets/tiles/sparse204/1-0-1.png
  test/integration/assets/tiles/sparse204/1-1-0.mvt
  test/integration/assets/tiles/sparse204/1-1-0.png
  test/integration/assets/tiles/sparse204/1-1-1.mvt
  test/integration/assets/tiles/sparse204/1-1-1.png
  test/integration/render/render.test.ts
  test/integration/render/tests/sparse-tileset/overdraw204/expected.png
  test/integration/render/tests/sparse-tileset/overdraw204/style.json
  test/integration/render/tests/sparse-tileset/rasterbase/expected.png
  test/integration/render/tests/sparse-tileset/rasterbase/style.json
  test/integration/render/tests/sparse-tileset/rasterfallback/expected.png
  test/integration/render/tests/sparse-tileset/rasterfallback/style.json
  test/integration/render/tests/sparse-tileset/rasterfallback204/expected.png
  test/integration/render/tests/sparse-tileset/rasterfallback204/style.json
  test/integration/render/tests/sparse-tileset/vectorbase/expected.png
  test/integration/render/tests/sparse-tileset/vectorbase/style.json
Labels: need more info

#1395 Make showTileBoundaries prefer a vector source
  CHANGELOG.md
  src/render/draw_debug.test.ts
  src/render/draw_debug.ts
  src/render/painter.ts
  test/integration/render/tests/debug/tile-raster/expected.png
  test/integration/render/tests/debug/tile-raster/style.json
Labels: waiting for code review fixes

#1632 map.setStyle's transformStyle option
  CHANGELOG.md
  src/style/style.test.ts
  src/style/style.ts
  src/ui/map.test.ts
  src/ui/map.ts
  test/debug-pages/transform-style.html
Labels: waiting for code review fixes

#1578 Remove elevationOffset and fix below sea-level clipping
  src/geo/transform.test.ts
  src/geo/transform.ts
  src/render/program/terrain_program.ts
  src/render/terrain.test.ts
  src/render/terrain.ts
  src/shaders/_prelude.vertex.glsl
  src/style-spec/reference/v8.json
  src/style-spec/validate/validate_terrain.test.ts
  src/ui/control/terrain_control.ts
  src/ui/map.ts
  test/debug-pages/terrain-satellite.html
  test/integration/render/tests/terrain/default/style.json
  test/integration/style-spec/tests/terrain.input.json
  test/integration/style-spec/tests/terrain.output.json
Labels: Terrain 3D

#1394 Fix parameter types of Map.querySourceFeatures
  src/source/query_features.test.ts
  src/source/query_features.ts
  src/source/tile.ts
  src/style/style.ts
  src/ui/map.ts
Labels: need more info

#1322 Add bench custom layer
  test/bench/benchmarks/customlayer.ts
  test/bench/versions/benchmarks.ts
Labels: need more info
