Repository maplibre/maplibre-gl-js, pull requests merged in 2023-07, with the labels that each got.

#2674 Introduce max canvas size option and automatically limit pixel ratio
  CHANGELOG.md
  src/render/painter.ts
  src/ui/map.test.ts
  src/ui/map.ts
  src/util/test/mock_webgl.ts
  test/integration/render/run_render_tests.ts
  test/integration/render/tests/pixel-ratio/veryhigh/expected.png
  test/integration/render/tests/pixel-ratio/veryhigh/style.json
Labels: need more info, waiting for code review fixes

#2857 Remove cooperative gesture screen from accessibility tree
  CHANGELOG.md
  src/ui/map.test.ts
  src/ui/map.ts
Labels: need more info

#1874 VectorTileWorkerSource: change reloadTile behavior to reload right away instead of waiting for previous parse to complete
  CHANGELOG.md
  src/source/vector_tile_worker_source.test.ts
  src/source/vector_tile_worker_source.ts
  src/source/worker_tile.test.ts
  src/source/worker_tile.ts
Labels: waiting for code review fixes
