Repository maplibre/maplibre-gl-js, pull requests merged in 2023-04, with the labels that each got.

#2324 Readability and code clean up in loadSprite
  src/style/load_sprite.ts
  src/util/style.test.ts
  src/util/style.ts
Labels: waiting for code review fixes

#2377 Cancel unloaded tile request on zooming in across multiple zoom
  CHANGELOG.md
  src/source/source_cache.test.ts
  src/source/source_cache.ts
Labels: need more info

#2381 Don't reload raster sources when RTL text plugin loads to avoid flicker.
  CHANGELOG.md
  src/source/rtl_text_plugin.ts
  src/style/style.test.ts
  src/style/style.ts
Labels: waiting for code review fixes

#2393 Fix: Handle AddProtocol callback function returning a HTMLImageElement
  CHANGELOG.md
  src/index.test.ts
  src/index.ts
  src/util/ajax.ts
  src/util/config.ts
  src/util/image_request.ts
Labels: waiting for code review fixes

#1672 Implement stencil logic for render-to-texture tiles
  src/gl/context.ts
  src/gl/framebuffer.ts
  src/gl/render_pool.ts
  src/gl/value.ts
  src/render/draw_heatmap.ts
  src/render/draw_hillshade.ts
  src/render/render_to_texture.ts
  src/render/terrain.ts
  test/integration/assets/tiles/terrain-shading/11-1086-714.terrain.png
  test/integration/assets/tiles/terrain-shading/11-1086-715.terrain.png
  test/integration/assets/tiles/terrain-shading/11-1086-716.terrain.png
  test/integration/assets/tiles/terrain-shading/11-1087-714.terrain.png
  test/integration/assets/tiles/terrain-shading/11-1087-715.terrain.png
  test/integration/assets/tiles/terrain-shading/11-1087-716.terrain.png
  test/integration/assets/tiles/terrain-shading/11-1088-714.terrain.png
  test/integration/assets/tiles/terrain-shading/11-1088-715.terrain.png
  test/integration/assets/tiles/terrain-shading/5-16-11.terrain.png
  test/integration/assets/tiles/terrain-shading/5-17-11.terrain.png
  test/integration/assets/tiles/terrain-shading/9-271-178.terrain.png
  test/integration/assets/tiles/terrain-shading/9-271-179.terrain.png
  test/integration/assets/tiles/terrain-shading/9-272-178.terrain.png
  test/integration/render/tests/terrain-shading/default/expected.png
  test/integration/render/tests/terrain-shading/default/style.json
Labels: Terrain 3D

#2354 Improve control performance by restricting worker count to a max of 1 except Safari
  CHANGELOG.md
  src/index.ts
  src/util/worker_pool.ts
Labels: waiting for code review fixes

#2126 Using HTMLImageElement for raster images
  CHANGELOG.md
  src/source/raster_dem_tile_source.ts
  src/source/raster_tile_source.test.ts
  src/source/raster_tile_source.ts
  src/util/ajax.ts
  src/util/image_request.test.ts
  src/util/image_request.ts
  src/util/test/util.ts
Labels: waiting for code review fixes
