Repository maplibre/maplibre-gl-js, pull requests merged in 2024-11, with the labels that each got.

#4937 Globe covering tiles optimization
  CHANGELOG.md
  src/geo/projection/covering_tiles.ts
  src/geo/projection/covering_tiles_details_provider.ts
  src/geo/projection/globe_covering_tiles.test.ts
  src/geo/projection/globe_covering_tiles_details_provider.ts
  src/geo/projection/globe_transform.ts
  src/geo/projection/mercator_covering_tiles_details_provider.ts
  src/geo/projection/mercator_transform.ts
  src/geo/transform_interface.ts
  src/util/primitives.ts
  src/util/primitives/aabb.ts
  src/util/primitives/aabb_cache.test.ts
  src/util/primitives/aabb_cache.ts
  src/util/primitives/frustum.ts
  src/util/primitives/primitives.test.ts
  test/bench/benchmarks/covering_tiles_globe.ts
  test/bench/versions/index.ts
  test/build/min.test.ts
Labels: Globe

#4897 Fixes scale control for globe on zoom out
  CHANGELOG.md
  src/ui/control/scale_control.ts
Labels: waiting for code review fixes

#4868 Globe: Tile borders fix
  CHANGELOG.md
  src/geo/projection/globe.ts
  src/render/draw_fill.ts
  src/shaders/_projection_globe.vertex.glsl
  src/shaders/_projection_mercator.vertex.glsl
  src/shaders/fill.vertex.glsl
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_pattern.vertex.glsl
  src/shaders/fill_outline.vertex.glsl
  src/shaders/fill_outline_pattern.vertex.glsl
  src/shaders/fill_pattern.vertex.glsl
  src/shaders/hillshade.vertex.glsl
  src/shaders/raster.vertex.glsl
  test/build/min.test.ts
  test/integration/assets/tiles/outside_ring.mvt
  test/integration/render/tests/fill-outside-tile/expected.png
  test/integration/render/tests/fill-outside-tile/style.json
  test/integration/render/tests/projection/globe/fill-planet-pole/expected_flaky.png
  test/integration/render/tests/projection/globe/fill-seams/checkerboard/expected-win2.png
  test/integration/render/tests/projection/globe/raster-pole/expected-win2.png
  test/integration/render/tests/projection/globe/raster-warped/expected-win-flaky8.png
  test/integration/render/tests/projection/globe/raster-warped/expected-win-flaky9.png
  test/integration/render/tests/projection/globe/terrain/fill-planet-pole/expected-windows-flaky.png
  test/integration/render/tests/symbol-visibility/visible/expected-win.png
Labels: globe

#5027 Fix renderWorldCopies regression
  src/geo/projection/covering_tiles.ts
  src/geo/projection/covering_tiles_details_provider.ts
  src/geo/projection/globe_covering_tiles_details_provider.ts
  src/geo/projection/globe_transform.ts
  src/geo/projection/mercator_covering_tiles_details_provider.ts
Labels: waiting for code review fixes

#5092 Fix unwanted roll #5083
  CHANGELOG.md
  src/geo/projection/camera_helper.ts
  src/geo/projection/globe_camera_helper.ts
  src/geo/projection/mercator_camera_helper.ts
  src/ui/camera.test.ts
  src/util/util.ts
Labels: waiting for code review fixes
